[package]
name = "print-qr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = { version = "0.13", default-features = false }
strip-ansi-escapes = "0.2.0"
